title: 'Taliia | The One From Septermber'
cta:
  domain: null
  version: null
  bucket: null
layout_spectrum: 1
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/fe4130bb-f32f-47f0-930b-bcead61279bb.png'
name: TALIIA
purpose: []
analytics:
  facebook: null
  google: UA-57894181-1
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  lightness: 0.606383
  saturation: 0
  rhythmicContrast: 0.6510639
  brandColors:
    - '#013741'
    - '#FFDAAD'
    - '#3FF3F9'
    - '#FF0000'
    - '#B98151'
typography_spectrum: 0.89816
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/2193cf79-ef84-45bf-ac4e-d44319058306.png'
