name: TALIIA
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fe4130bb-f32f-47f0-930b-bcead61279bb.png
layout_spectrum: 0.48998
typography_spectrum: 0.89816
title: Taliia
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2193cf79-ef84-45bf-ac4e-d44319058306.png
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-57894181-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc1682'
    - '#feef35'
    - '#2e79fb'
    - '#23cdfd'
    - '#44085f'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
