name: TALIIA
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/fe4130bb-f32f-47f0-930b-bcead61279bb.png'
layout_spectrum: 0.5104
typography_spectrum: 0.89816
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/2193cf79-ef84-45bf-ac4e-d44319058306.png'
title: Pop Artist
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-57894181-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00e3fe'
    - '#008abb'
    - '#002f40'
    - '#005f75'
  brandStrength: 0
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
